{{- if not .Values.kaneo.env.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaneo.fullname" . }}-auth
  labels:
    {{- include "kaneo.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-secret: {{ .Values.kaneo.env.authSecret | quote }}
{{- end }}
{{- if not .Values.kaneo.env.notificationSecretExistingSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaneo.fullname" . }}-notification
  labels:
    {{- include "kaneo.labels" . | nindent 4 }}
type: Opaque
stringData:
  notification-encryption-key: {{ .Values.kaneo.env.notificationSecretEncryptionKey | quote }}
{{- end }}
{{- if and (not .Values.minio.enabled) (not .Values.kaneo.env.s3.existingSecret.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaneo.fullname" . }}-s3
  labels:
    {{- include "kaneo.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.kaneo.env.s3.accessKeyId | quote }}
  secret-access-key: {{ .Values.kaneo.env.s3.secretAccessKey | quote }}
{{- end }}
